apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: default
data:
  appsettings.json: |-
    {
      "Settings": {
        "KeyOne": "new prompt",
        "KeyTwo": 100
      }
    }